import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx,js,jsx}", "./components/**/*.{ts,tsx,js,jsx}", "./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        outfit: ["Outfit", "sans-serif"],
        syne: ["Outfit", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        charcoal: "hsl(var(--charcoal))",
        yellow: "hsl(var(--yellow))",
        teal: "hsl(var(--teal))",
        orange: "hsl(var(--orange))",
        maroon: "hsl(var(--maroon))",
        p100: "hsl(var(--p100))",
        p300: "hsl(var(--p300))",
        p400: "hsl(var(--p400))",
        p500: "hsl(var(--p500))",
        p600: "hsl(var(--p600))",
        p700: "hsl(var(--p700))",
        p800: "hsl(var(--p800))",
        p900: "hsl(var(--p900))",
        "dark-charcoal-bg": "hsl(var(--dark-charcoal-bg))",
        "dark-charcoal-fg": "hsl(var(--dark-charcoal-fg))",
        "dark-gold-card-bg": "hsl(var(--dark-gold-card-bg))",
        "dark-gold-card-fg": "hsl(var(--dark-gold-card-fg))",
        "dark-maroon-bg": "hsl(var(--dark-maroon-bg))",
        "dark-maroon-fg": "hsl(var(--dark-maroon-fg))",
        "dark-purple-bg": "hsl(var(--dark-purple-bg))",
        "dark-purple-fg": "hsl(var(--dark-purple-fg))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
} satisfies Config;
